### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by vanodevium** [dcoffey-zengenti/node-rdap#2]
Node: 
```sh
node --version
v18.17.1

```

node-rdap lib:
```
"node-rdap": "0.3.5"
```

---

When I start my long-run process then I see:

```sh
(node:447654) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Keyv]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:588:17)
    at Keyv.addListener (node:events:606:10)
    at Keyv.once (node:events:650:8)
    at file:///path/to/project/node_modules/cacheable-request/dist/index.js:193:28
    at file:///path/to/project/node_modules/cacheable-request/dist/index.js:206:15
    at file:///path/to/project/node_modules/got/dist/source/core/index.js:888:67
    at new Promise (<anonymous>)
    at _createCacheableRequest (file:///path/to/project/node_modules/got/dist/source/core/index.js:883:16)
    at Request._makeRequest (file:///path/to/project/node_modules/got/dist/source/core/index.js:964:37)
```

As I understand, the main problem is at **Keyv** cache and **got**.
But maybe you can set up **maxListeners** from the library?

**Comment by dcoffey-zengenti** [comment]
I have replaced got with native fetch, which should solve this issue.
